### PR TITLE
Fix websocket

### LINKED ISSUE #67: No websocket support?
Wanted to try out devroom.mindeco.de but it appears that web sockets is not enabled, is that correct? I sneakily tried to just replace net with wss ;-)

### LINKED ISSUE #117: Hosting documentation: HTTP(S) Proxy
We currently assume a standard HTTPS server in front of go-ssb-room to facilitate TLS termination and certificate management. This should be possible with most modern HTTP servers since it's a pretty standard practice, known as [reverse proxying](https://en.wikipedia.org/wiki/Reverse_proxy).

Two bits of rational:

1) People usually want to have more then one site on their server. Put differently we could have LetsEncrypt inside the go-ssb-room server but it would have to listen on port :443, blocking the use of other domains on the same IP.
2) Listening on :443 can be pretty annoying (you might need root priviliges or similar capabilities).

go-ssb-room needs three headers to function properly, which need to be forwarded by the webserver.

* `X-Forwarded-Host` as which domain name the room is running (enforce strict TLS checking)
* `X-Forwarded-Proto` to ensure that TLS is used (and redirect if necessary)
* `X-Forwarded-For` the remote IP address of the client accessing the room (used for rate limiting)

Here are three examples using common sever software:

# Nginx

**TODO: Needs websocket and error handlers**

https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/

Here is what we are using on hermies.club:

```
server {
    server_name hermies.club;

    listen 443 ssl; # managed by Certbot

    ssl_certificate /etc/letsencrypt/live/hermies.club/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/hermies.club/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://localhost:8899;
    }

    # TODO: https://nginx.org/en/docs/http/websocket.html
    # TODO: https://blog.tarq.io/nginx-catch-all-error-pages/
}

server {
    server_name "~^(?<alias>\w+)\.hermies\.club$";

    listen 443 ssl; # managed by Certbot

    ssl_certificate /etc/letsencrypt/live/hermies.club/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/hermies.club/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    location = / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://localhost:8899/alias/$alias;
    }

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://localhost:8899;
    }

    # TODO: https://blog.tarq.io/nginx-catch-all-error-pages/
}



server {
    if ($host ~ hermies.club$ ) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80 default_server;
    listen [::]:80 default_server;
    server_name hermies.club;
    return 404; # managed by Certbot
}
```

# Apache

**TODO: untested, needs complete header settings**

https://www.digitalocean.com/community/tutorials/how-to-use-apache-as-a-reverse-proxy-with-mod_proxy-on-ubuntu-16-04

Snippet. Should be something like:

```
<VirtualHost devroom.mindeco.de:443>
    ProxyPreserveHost On

    ProxyPass / http://127.0.0.1:8000/
    ProxyPassReverse / http://127.0.0.1:8000/
</VirtualHost>
```

# [Caddy](caddyserver.com/)

Pretty default [reverse_proxy](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy) 

Here is what we are using for `devroom.mindeco.de`, which is our test server.

`devroom.mindeco.de` is the TLS domain of the room and `localhost:8000` is the `-lishttp` go-ssb-room is using.

TODO:

* redirecting aliases form subdomain to url

```
devroom.mindeco.de {
        reverse_proxy localhost:8000 {
                header_up Host {host}
                header_up Origin {host}
                header_up X-Forwarded-Host {host}
        }

        # optional to use http.cat but
        # having an error handler is good practice i.e.
        # if the room server is down for maintenance
        handle_errors {
                rewrite * /{http.error.status_code}
                reverse_proxy https://http.cat {
                        header_up Host http.cat
                }
        }
}
```

`X-Forwarded-For` and `X-Forwarded-Proto` are set and forwarded by default here.

### PR DESCRIPTION
**Pull request by cryptix**
* [x] hookup the  HTTP to Websocket to shs+muxrpc upgrade code to the landing page (enables use with ssb-ws). (fixes #67)
* [x] Add a simple test to muxrpc/test/go
* [x] Add documentation about HTTP(S) hosting to the `docs/` folder (fixes #117)

### CODE REVIEW

**Comment by cblgh** [comment]
guessing this closes #67?

File: internal/network/interface.go [hunk 1]
```diff
@@ -97,8 +97,11 @@ type Network interface {
 
 	GetConnTracker() ConnTracker
 
-	// websock hack
-	HandleHTTP(handler http.Handler)
+	// WebsockHandler returns a "middleware" like thing that is able to upgrade a websocket request to a muxrpc connection and authenticate using shs.
```
Comment (staltz) [inline internal/network/interface.go:100]:
```suggestion
	// WebsockHandler returns a "middleware" like thing that is able to upgrade a 
 	// websocket request to a muxrpc connection and authenticate using shs.
```

Comment (staltz) [reply internal/network/interface.go:100]: Just a line break

File: internal/network/websocket.go [hunk 2]
```diff
@@ -10,128 +10,175 @@ import (
...
 	"time"
 
+	kitlog "github.com/go-kit/kit/log"
 	"github.com/go-kit/kit/log/level"
 	"github.com/gorilla/websocket"
 	"go.cryptoscope.co/muxrpc/v2"
 )
 
-func websockHandler(n *node) http.HandlerFunc {
+// WebsockHandler returns a "middleware" like thing that is able to upgrade a websocket request to a muxrpc connection and authenticate using shs.
```
Comment (staltz) [inline internal/network/websocket.go:19]:
```suggestion
// WebsockHandler returns a "middleware" like thing that is able to upgrade a
// websocket request to a muxrpc connection and authenticate using shs.
```

File: internal/network/websocket.go [hunk 3]
```diff
@@ -10,128 +10,175 @@ import (
...
+func (n *node) WebsockHandler(next http.Handler) http.Handler {
 	var upgrader = websocket.Upgrader{
 		ReadBufferSize:  1024 * 4,
 		WriteBufferSize: 1024 * 4,
+
 		CheckOrigin: func(_ *http.Request) bool {
 			return true
 		},
+
+		// 99% of the traffic will be ciphertext which is impossible to distingish from randomness and thus also hard to compress
```
Comment (staltz) [inline internal/network/websocket.go:32]:
```suggestion
		// 99% of the traffic will be ciphertext which is impossible to distingish
		// from randomness and thus also hard to compress
```

File: muxrpc/handlers/tunnel/server/connect.go [hunk 4]
```diff
@@ -21,6 +23,7 @@ type connectArg struct {
 type connectWithOriginArg struct {
 	connectArg
 	Origin refs.FeedRef `json:"origin"` // this should be clear from the shs session already
+	Caller refs.FeedRef `json:"caller"` // who started the call
```
Comment (staltz) [inline muxrpc/handlers/tunnel/server/connect.go:26]: Is this the same as Portal? Given that there are just 3 peers, which one is the Caller? (Portal, Target, or Origin?)

**Review by staltz — APPROVED** [review]
Just some questions and code-comment suggestions, otherwise LGTM

File: docs/README.md [hunk 5]
```diff
@@ -17,3 +17,20 @@ This implementation is compliant with [SSB HTTP Authentication](https://github.c
 A summary can be seen in the following chart:
 
 ![Chart](./login-chart.png)
+
+# HTTP Hosting
+
+We currently assume a standard HTTPS server in front of go-ssb-room to facilitate TLS termination and certificate management. This should be possible with most modern HTTP servers since it's a pretty standard practice, known as [reverse proxying](https://en.wikipedia.org/wiki/Reverse_proxy).
+
+Two bits of rational:
```
Comment (cblgh) [inline docs/README.md:25]:
```suggestion
Two bits of rationale:
```

File: docs/README.md [hunk 6]
```diff
@@ -17,3 +17,20 @@ This implementation is compliant with [SSB HTTP Authentication](https://github.c
...
+
+1) People usually want to have more then one site on their server. Put differently we could have LetsEncrypt inside the go-ssb-room server but it would have to listen on port :443, blocking the use of other domains on the same IP.
```
Comment (cblgh) [inline docs/README.md:27]:
```suggestion
1) People usually want to have more than one site on their server. Put differently, we could have [LetsEncrypt](https://letsencrypt.org/) inside the go-ssb-room server but it would have to listen on port :443—blocking the use of other domains on the same IP.
```

fixing typo and then just doing some extras while im at it

File: docs/README.md [hunk 7]
```diff
@@ -17,3 +17,20 @@ This implementation is compliant with [SSB HTTP Authentication](https://github.c
...
+2) Listening on :443 can be pretty annoying (you might need root priviliges or similar capabilities).
```
Comment (cblgh) [inline docs/README.md:28]:
```suggestion
2) Listening on :443 can be pretty annoying (you might need root privileges or similar capabilities).
```

File: docs/README.md [hunk 8]
```diff
@@ -17,3 +17,20 @@ This implementation is compliant with [SSB HTTP Authentication](https://github.c
...
+
+go-ssb-room needs three headers to function properly, which need to be forwarded by the webserver.
+
+* `X-Forwarded-Host` as which domain name the room is running (enforce strict TLS checking)
+* `X-Forwarded-Proto` to ensure that TLS is used (and redirect if necessary)
+* `X-Forwarded-For` the remote TCP/IP address of the client accessing the room (used for rate limiting)
+
+[nginx-example.conf](./nginx-example.conf) contains an [nginx](https://nginx.org) config that we use for `hermies.club`. To get a wildcard TLS certificate you can follow the steps in [this](https://medium.com/@alitou/getting-a-wildcard-ssl-certificate-using-certbot-and-deploy-on-nginx-15b8ffa34157) article which uses the [certbot](https://certbot.eff.org/) utility.
```
Comment (cblgh) [inline docs/README.md:36]:
```suggestion
[nginx-example.conf](./nginx-example.conf) contains an [nginx](https://nginx.org) config that we use for [hermies.club](https://hermies.club). To get a wildcard TLS certificate you can follow the steps in [this article](https://medium.com/@alitou/getting-a-wildcard-ssl-certificate-using-certbot-and-deploy-on-nginx-15b8ffa34157), which uses the [certbot](https://certbot.eff.org/) utility.

Comment (cblgh) [reply docs/README.md:36]: btw super super super nice to provide a config, this will make life 1000x easier for folx 🖤

File: internal/network/websocket.go (hunk 3 above)
Comment (cblgh) [reply internal/network/websocket.go:32]: i fixed the typo in distinguish, in addition to andre's suggestion

File: muxrpc/handlers/gossip/ping.go [hunk 9]
```diff
@@ -19,7 +19,7 @@ import (
 //
 func Ping(ctx context.Context, req *muxrpc.Request, peerSrc *muxrpc.ByteSource, peerSnk *muxrpc.ByteSink) error {
 	type arg struct {
-		Timeout int
+		Timeout int // not actually a "timeout" but the delay between two pings
```
Comment (cblgh) [inline muxrpc/handlers/gossip/ping.go:22]: why not call it delay, then?

File: muxrpc/handlers/gossip/ping.go [hunk 10]
```diff
@@ -48,27 +62,42 @@ func Ping(ctx context.Context, req *muxrpc.Request, peerSrc *muxrpc.ByteSource,
...
+			err := peerSrc.Reader(func(rd io.Reader) error {
+				return json.NewDecoder(rd).Decode(&ping)
+			})
+			if err != nil {
+				receiveErr <- err
+				return
+			}
+
+			// when := time.Time(ping)
+			// fmt.Printf("got ping: %s - age: %s\n", when.String(), time.Since(when))
```
Comment (cblgh) [inline muxrpc/handlers/gossip/ping.go:87]:
```suggestion
```

or useful as a debug util?

**Review by cblgh — APPROVED** [review]
go go go

File: muxrpc/handlers/gossip/ping.go (hunk 9 above)
Comment (cryptix) [reply muxrpc/handlers/gossip/ping.go:22]: Right! we can do this to keep this side of the code clean/comprehensible. 

```go
type arg struct {
		Delay int `json:"timeout"`
}
```

File: muxrpc/handlers/tunnel/server/connect.go (hunk 4 above)
Comment (cryptix) [reply muxrpc/handlers/tunnel/server/connect.go:26]: This addition was a bit inconsiderate and out of frustration. Just to recap my understanding:

* Portal: the room server.
* Target: the peer the initiator (or origin) want's to connect to.
* Origin: the peer who made the initial `tunnel.connect` towards the room.

What I have been seeing is that portal == origin and the missing bit for the receiver of the request (the target) was who the caller was, which can only be learned after shs handshake completes, unless the server already notifies the target via the proposed new `caller` argument.

I just added a new one because I wasn't sure if the JS implementation needs any of these so I didnt want to mess with this but from your comment I assume that it's okay to fix Origin to be Caller and not Portal, then.

My frustration stemmed from this:

* Portal: is irrelevant for the room as well as the target
  * the room knows who it is
  * the target/receiver knows who the request is from via shs auth
* Target: only relevant for the room and doesn't need to be forwarded (the target knows who it is)
* Origin: only info that needs to be forwarded to the target but should be set by the origin itself (can be set by the server which takes it from shs auth)

Comment (staltz) [reply muxrpc/handlers/tunnel/server/connect.go]: I think the redundancy you felt with `Portal` was because ssb-tunnel was originally built so that one `index.js` can be used for all of those 3 roles.
